name: deploy_to_firebase_hosting

on:
  push:
    tags:
      - release-production-*

jobs:
  deploy_to_firebase_hosting:

    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@main
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
